### PR TITLE
feat: add edit and redirect to detail page feature

### PR DESCRIPTION
**Pull request by desup1421**
Try to fix vercel problem too.

ref: #5

### CODE REVIEW

**Review by muhamademiralfani — CHANGES_REQUESTED** [review]
Data is not removed from the list when an item is deleted.

**Comment by desup1421** [comment]
I fixed the problem, please check my revision.

**Review by kevinpang14 — APPROVED** [review]
Approved new Featured

**Review by muhamademiralfani — APPROVED** [review]
Approved!

**Pull request merged**
